[2024-11-28T15:07:07.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T15:07:07.444+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: github_repo_check.check_repo scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-11-28T15:07:07.452+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: github_repo_check.check_repo scheduled__2024-09-25T00:00:00+00:00 [queued]>
[2024-11-28T15:07:07.453+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T15:07:07.464+0000] {taskinstance.py:2889} INFO - Executing <Task(GithubOperator): check_repo> on 2024-09-25 00:00:00+00:00
[2024-11-28T15:07:07.469+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1032) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-28T15:07:07.470+0000] {standard_task_runner.py:72} INFO - Started process 1045 to run task
[2024-11-28T15:07:07.472+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'github_repo_check', 'check_repo', 'scheduled__2024-09-25T00:00:00+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/github.py', '--cfg-path', '/tmp/tmpf70muugh']
[2024-11-28T15:07:07.473+0000] {standard_task_runner.py:105} INFO - Job 276: Subtask check_repo
[2024-11-28T15:07:07.521+0000] {task_command.py:467} INFO - Running <TaskInstance: github_repo_check.check_repo scheduled__2024-09-25T00:00:00+00:00 [running]> on host 080dcf124ece
[2024-11-28T15:07:07.592+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='github_repo_check' AIRFLOW_CTX_TASK_ID='check_repo' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-25T00:00:00+00:00'
[2024-11-28T15:07:07.593+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T15:07:07.613+0000] {base.py:84} INFO - Retrieving connection 'GitHub'
[2024-11-28T15:07:07.622+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 71, in execute
    github_result = getattr(resource, self.method_name)(**self.github_method_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Github.get_repo() got an unexpected keyword argument 'yahadpas@gmail.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 80, in execute
    raise AirflowException(f"GitHub operator error: {e}")
airflow.exceptions.AirflowException: GitHub operator error: Github.get_repo() got an unexpected keyword argument 'yahadpas@gmail.com'
[2024-11-28T15:07:07.625+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=github_repo_check, task_id=check_repo, run_id=scheduled__2024-09-25T00:00:00+00:00, execution_date=20240925T000000, start_date=20241128T150707, end_date=20241128T150707
[2024-11-28T15:07:07.633+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T15:07:07.634+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 276 for task check_repo (GitHub operator error: Github.get_repo() got an unexpected keyword argument 'yahadpas@gmail.com'; 1045)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 71, in execute
    github_result = getattr(resource, self.method_name)(**self.github_method_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Github.get_repo() got an unexpected keyword argument 'yahadpas@gmail.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/github/operators/github.py", line 80, in execute
    raise AirflowException(f"GitHub operator error: {e}")
airflow.exceptions.AirflowException: GitHub operator error: Github.get_repo() got an unexpected keyword argument 'yahadpas@gmail.com'
[2024-11-28T15:07:07.653+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T15:07:07.665+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T15:07:07.666+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
